#!/bin/bash
# Environment variables
DITOR=vi;export EDITOR
ORACLE_SID=BBDB;export ORACLE_SID
ORACLE_BASE=/orasw; export ORACLE_BASE
ORACLE_HOME=$ORACLE_BASE/product/10GR2; export ORACLE_HOME
LD_LIBRARY_PATH=$ORACLE_HOME/lib:$ORACLE_HOME/ctx/lib:/usr/lib; export LD_LIBRARY_PATH
PATH=/usr/bin:/usr/sbin:/usr/ucb:/usr/ccs/bin:/usr/local/bin:$ORACLE_HOME/bin:$ORACLE_HOME/OPatch; export PATH

sessionsQ="select count(session_id) from bb_bb60.sessions;"

echo "set feedback off verify off heading off pagesize 0
  $sessionsQ
  exit" | $ORACLE_HOME/bin/sqlplus -s bb_bb60/utpass@BBDB | while read output ;
  do
   echo "bb_sessions "$output
  done
